"""Unit tests for PDF parsing + chunking logic.

These tests use synthetic PDFs generated by PyMuPDF so they don't depend
on external files. They verify the parser and chunker produce sensible
output for various paper-like structures.
"""

from __future__ import annotations

import fitz
import pytest

from app.domains.artifact.chunker import chunk_parsed_pdf
from app.domains.artifact.pdf_parser import parse_pdf


def _make_pdf(pages: list[str], *, with_headings: bool = False) -> bytes:
    """Build a PDF with the given page texts.

    Uses insert_textbox with a large rectangle so all text is preserved
    (insert_text clips at page boundary by default).

    If with_headings=True, render the first line of each page with a larger
    font to simulate a section heading.
    """
    doc = fitz.open()
    for page_text in pages:
        page = doc.new_page()
        # Use a near-full-page textbox so long text isn't clipped.
        rect = fitz.Rect(36, 36, page.rect.width - 36, page.rect.height - 36)
        if with_headings and "\n" in page_text:
            first_line, rest = page_text.split("\n", 1)
            # Heading in a small top rect with larger font.
            heading_rect = fitz.Rect(36, 36, page.rect.width - 36, 80)
            page.insert_textbox(heading_rect, first_line, fontsize=14, fontname="hebo")
            body_rect = fitz.Rect(36, 90, page.rect.width - 36, page.rect.height - 36)
            page.insert_textbox(body_rect, rest, fontsize=10, fontname="helv")
        else:
            page.insert_textbox(rect, page_text, fontsize=10, fontname="helv")
    return doc.tobytes()


# ------------------------------------------------------------- pdf_parser
def test_parse_pdf_extracts_text() -> None:
    pdf = _make_pdf(["Hello world. This is a test paragraph."])
    parsed = parse_pdf(pdf)
    assert parsed.page_count == 1
    assert "Hello world" in parsed.full_text
    assert len(parsed.page_char_ranges) == 1


def test_parse_pdf_handles_empty_pdf() -> None:
    doc = fitz.open()
    doc.new_page()  # one blank page
    pdf = doc.tobytes()
    parsed = parse_pdf(pdf)
    assert parsed.page_count == 1
    assert parsed.full_text.strip() == ""
    assert parsed.sections == []


def test_parse_pdf_handles_invalid_bytes() -> None:
    parsed = parse_pdf(b"not a pdf at all")
    assert parsed.page_count == 0
    assert parsed.full_text == ""
    # Should NOT raise - just return empty result with warnings.
    assert len(parsed.warnings) > 0


def test_parse_pdf_fixes_broken_hyphenation() -> None:
    # PyMuPDF's text extraction typically puts hyphenated line breaks as "opti-\nmization"
    # We can't easily reproduce this with insert_text (it doesn't wrap), but
    # we can test the cleaning function directly.
    from app.domains.artifact.pdf_parser import _clean_page_text

    cleaned = _clean_page_text("opti-\nmization is great")
    assert "optimization" in cleaned
    assert "opti-" not in cleaned


def test_parse_pdf_removes_citation_brackets() -> None:
    from app.domains.artifact.pdf_parser import _clean_page_text

    cleaned = _clean_page_text("GNNs [12] are powerful [13, 15].")
    assert "[12]" not in cleaned
    assert "[13, 15]" not in cleaned
    assert "GNNs" in cleaned


def test_parse_pdf_detects_sections() -> None:
    pdf = _make_pdf(
        [
            "Abstract\nWe propose a new method for GNN explainability.\n",
            "1. Introduction\nGNNs are widely used. We want to explain them.\n",
            "2. Method\nOur method uses mutual information.\n",
        ],
        with_headings=True,
    )
    parsed = parse_pdf(pdf)
    section_names = [s.section for s in parsed.sections]
    # We should detect at least some of these (detection is best-effort).
    # The exact subset depends on PyMuPDF's heading detection.
    assert len(parsed.sections) >= 1


def test_parse_pdf_multi_page_char_ranges() -> None:
    pdf = _make_pdf(["page one content", "page two content", "page three"])
    parsed = parse_pdf(pdf)
    assert parsed.page_count == 3
    assert len(parsed.page_char_ranges) == 3
    # Each range should be non-empty and in document order.
    for start, end in parsed.page_char_ranges:
        assert end > start
    # Ranges should be monotonically increasing.
    starts = [r[0] for r in parsed.page_char_ranges]
    assert starts == sorted(starts)


# --------------------------------------------------------------- chunker
def _chunk_from(
    parsed,
    *,
    workspace_id="ws-1",
    paper_id="paper-1",
    artifact_id="art-1",
    created_at="2026-07-19T10:00:00Z",
):
    return chunk_parsed_pdf(
        parsed,
        workspace_id=workspace_id,
        paper_id=paper_id,
        artifact_id=artifact_id,
        created_at=created_at,
    )


def test_chunker_empty_pdf_produces_no_chunks() -> None:
    parsed = parse_pdf(b"")
    chunks = _chunk_from(parsed)
    assert chunks == []


def test_chunker_short_text_produces_one_chunk() -> None:
    pdf = _make_pdf(["This is a short paragraph. It is too short to split."])
    parsed = parse_pdf(pdf)
    chunks = _chunk_from(parsed)
    assert len(chunks) >= 1
    # All chunks should have required fields populated.
    for c in chunks:
        assert c.chunk_id
        assert c.workspace_id == "ws-1"
        assert c.paper_id == "paper-1"
        assert c.artifact_id == "art-1"
        assert c.text
        assert c.start_char < c.end_char
        assert c.tokens_estimate > 0
        assert c.chunk_version == "v1"


def test_chunker_chunk_index_is_sequential() -> None:
    # Make a PDF with several long paragraphs across multiple pages to get
    # multiple chunks. Use 4 pages to exceed PyMuPDF's per-page text wrapping.
    pages = []
    for i in range(4):
        # ~2000 chars per page, well over TARGET_CHARS (2048) per chunk
        pages.append(f"Page {i+1}. " + "This is paragraph content. " * 100)
    pdf = _make_pdf(pages)
    parsed = parse_pdf(pdf)
    chunks = _chunk_from(parsed)
    assert len(chunks) >= 2
    indices = [c.chunk_index for c in chunks]
    assert indices == list(range(len(chunks)))


def test_chunker_respects_min_chunk_size() -> None:
    # Craft text where naive splitting would produce tiny tail chunks.
    text = "Main paragraph here. " * 100 + "\n\n" + "tiny."
    pdf = _make_pdf([text])
    parsed = parse_pdf(pdf)
    chunks = _chunk_from(parsed)
    # No chunk should be tiny (the tail "tiny." should be merged).
    for c in chunks:
        # Allow some tolerance - merged chunks are fine, but no orphans.
        assert c.tokens_estimate > 0


def test_chunker_chunks_have_unique_ids() -> None:
    pdf = _make_pdf(["Paragraph A. " * 200 + "\n\n" + "Paragraph B. " * 200])
    parsed = parse_pdf(pdf)
    chunks = _chunk_from(parsed)
    ids = {c.chunk_id for c in chunks}
    assert len(ids) == len(chunks)


def test_chunker_section_assignment() -> None:
    # When sections are detected, chunks should carry section names.
    pdf = _make_pdf(
        [
            "Abstract\nWe propose X.\n" + "Body text. " * 100,
            "Introduction\nGNNs are great.\n" + "More body. " * 100,
        ],
        with_headings=True,
    )
    parsed = parse_pdf(pdf)
    chunks = _chunk_from(parsed)
    # If section detection worked, at least some chunks should have non-Unknown section.
    sections = {c.section for c in chunks}
    # Even if detection missed some, the union should be non-empty.
    assert sections
    # All chunks should have a section string (either known or "Unknown").
    for c in chunks:
        assert c.section is not None


def test_chunker_chunks_preserve_text_content() -> None:
    pdf = _make_pdf(["The quick brown fox jumps over the lazy dog. " * 50])
    parsed = parse_pdf(pdf)
    chunks = _chunk_from(parsed)
    # The union of chunk texts should cover the original key phrase.
    combined = " ".join(c.text for c in chunks)
    assert "quick brown fox" in combined


def test_chunker_page_numbers_are_valid() -> None:
    pdf = _make_pdf(["page 1 text " * 100, "page 2 text " * 100])
    parsed = parse_pdf(pdf)
    chunks = _chunk_from(parsed)
    for c in chunks:
        assert c.page_start >= 1
        assert c.page_end >= c.page_start
        assert c.page_start <= parsed.page_count
        assert c.page_end <= parsed.page_count


def test_chunker_overlap_makes_adjacent_chunks_share_text() -> None:
    # Make a long text that will definitely be split into multiple chunks.
    text = "Sentence one. " * 300
    pdf = _make_pdf([text])
    parsed = parse_pdf(pdf)
    chunks = _chunk_from(parsed)
    if len(chunks) >= 2:
        # Adjacent chunks should share some text via overlap.
        # Look at the tail of chunk[i] vs head of chunk[i+1].
        prev_tail = chunks[0].text[-50:]
        next_head = chunks[1].text[:50]
        # Find a substring of prev_tail that appears in next_head.
        # The overlap region should bridge the two.
        # (We don't assert exact overlap because chunk boundaries may land
        # at sentence boundaries where overlap is shorter.)
        # Just sanity-check: chunk[1] should start with text that existed in chunk[0].
        # If no overlap, chunk[1] starts mid-text.
        assert chunks[1].start_char <= chunks[0].end_char
